# Loyalty program Rails Service Declaration
apiVersion: v1
kind: Service
metadata:
  labels:
    app: loyalty-app
  name: loyalty-app-service
  namespace: loyalty-app
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: loyalty-app
